version: '3'

includes:
  python: ./provision/task/python.yml
  git: ./provision/task/git.yml
  docs: ./provision/task/docs.yml
  gitflow: ./provision/task/gitflow.yml
  version: ./provision/task/version.yml
  changelog: ./provision/task/changelog.yml

env:
  DOCKER:
    sh: docker -v
  PYTHON:
    sh: python --version
  APP_TAG:
    sh: git describe --tags $(git rev-list --tags --max-count=1) || echo "0.0.0"
  README_YAML: provision/generators/README.yaml
  README_TEMPLATE: provision/templates/README.tpl.md
  README_INCLUDES: file://

dotenv:
  - .env

vars:
  PROJECT_NAME: zsh-functions
  ORGANIZATION: hadenlabs
  REVIEWERS: luismayta
  PYTHON_VERSION: 3.9.2
  GIT_IGNORES: python,node,go,zsh
  README_FILE: README.md
  GIT_IGNORES_CUSTOM: >-
    bin
    TMP_CHANGELOG.md

tasks:
  default:
    deps:
      - task: check
    cmds:
      - cmd: echo Application {{.PROJECT_NAME}}
        silent: true
      - task: version:default
      - task: summary
    silent: true

  summary:
    desc: 'Summary information'
    cmds:
      - echo Docker available {{.DOCKER}}
    silent: true

  check:
    desc: 'Check all dependencies'
    deps:
      - python:check
      - changelog:check
      - git:check
      - gitflow:check
      - docs:check

  readme:
    run: once
    desc: Generate Readme
    silent: true
    cmds:
      - >-
        gomplate --file {{.README_TEMPLATE}}
        --out {{.README_FILE}}
        --datasource config={{.README_YAML}}
        --datasource includes={{.README_INCLUDES}}

  setup:
    desc: Setup dependences of project
    cmds:
      - task: python:setup
      - task: python:precommit
      - task: git:setup
      - task: gitflow:setup

  environment:
    desc: Setup environment of project
    cmds:
      - task: python:environment
